### ISSUE TITLE
UnionAggregate Queries Failing

### ISSUE THREAD

**Issue by cgivre** [k255/drill-gis#3]
I'm getting errors when I try to use the union aggregate function.  I have a CSV file with polygons as text.  The ST_GeomFromText() seems to work, but if I try to do the union aggregate as shown in the query below, I get the following errors:

```sql
SELECT ST_UnionAggregate( ST_GeomFromText( `st_astext` )) 
FROM dfs.`polygons.csvh` 
WHERE st_astext IS NOT NULL 
LIMIT 10;
```

```
Error: SYSTEM ERROR: SchemaChangeException: Failure while materializing expression. 
Error in expression at index -1.  Error: Missing function implementation: [st_unionaggregate(VARBINARY-REQUIRED)].  Full expression: --UNKNOWN EXPRESSION--.

Fragment 0:0

[Error Id: c217bf9b-3725-44ad-8098-d4be38a36930 on charless-mbp-2.fios-router.home:31010] (state=,code=0)
java.sql.SQLException: SYSTEM ERROR: SchemaChangeException: Failure while materializing expression. 
Error in expression at index -1.  Error: Missing function implementation: [st_unionaggregate(VARBINARY-REQUIRED)].  Full expression: --UNKNOWN EXPRESSION--.

Fragment 0:0

[Error Id: c217bf9b-3725-44ad-8098-d4be38a36930 on charless-mbp-2.fios-router.home:31010]
	at org.apache.drill.jdbc.impl.DrillCursor.nextRowInternally(DrillCursor.java:489)
	at org.apache.drill.jdbc.impl.DrillCursor.next(DrillCursor.java:593)
	at org.apache.calcite.avatica.AvaticaResultSet.next(AvaticaResultSet.java:215)
	at org.apache.drill.jdbc.impl.DrillResultSetImpl.next(DrillResultSetImpl.java:140)
	at sqlline.IncrementalRows.hasNext(IncrementalRows.java:62)
	at sqlline.TableOutputFormat$ResizingRowsProvider.next(TableOutputFormat.java:87)
	at sqlline.TableOutputFormat.print(TableOutputFormat.java:118)
	at sqlline.SqlLine.print(SqlLine.java:1593)
	at sqlline.Commands.execute(Commands.java:852)
	at sqlline.Commands.sql(Commands.java:751)
	at sqlline.SqlLine.dispatch(SqlLine.java:746)
	at sqlline.SqlLine.begin(SqlLine.java:621)
	at sqlline.SqlLine.start(SqlLine.java:375)
	at sqlline.SqlLine.main(SqlLine.java:268)
Caused by: org.apache.drill.common.exceptions.UserRemoteException: SYSTEM ERROR: SchemaChangeException: Failure while materializing expression. 
Error in expression at index -1.  Error: Missing function implementation: [st_unionaggregate(VARBINARY-REQUIRED)].  Full expression: --UNKNOWN EXPRESSION--.

Fragment 0:0

[Error Id: c217bf9b-3725-44ad-8098-d4be38a36930 on charless-mbp-2.fios-router.home:31010]
	at org.apache.drill.exec.rpc.user.QueryResultHandler.resultArrived(QueryResultHandler.java:123)
	at org.apache.drill.exec.rpc.user.UserClient.handle(UserClient.java:465)
	at org.apache.drill.exec.rpc.user.UserClient.handle(UserClient.java:102)
	at org.apache.drill.exec.rpc.RpcBus$InboundHandler.decode(RpcBus.java:274)
	at org.apache.drill.exec.rpc.RpcBus$InboundHandler.decode(RpcBus.java:244)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at java.lang.Thread.run(Thread.java:745)
```

I think the error might be caused by the input as being the `NullableVarBinaryHolder` instead of just a `VarBinaryHolder` but I'm not sure.

**Comment by k255** [comment]
Thanks! I've tested the union aggregate and made a fix for grouped queries and also provided quick tests. Please check it out and let me know if the problem persists. If so, please provide the file you're trying to query.

**Comment by cgivre** [comment]
Hi @k255 ,
Can you incorporate the fix into the PR for Drill?  
Thx!

**Comment by k255** [comment]
Hey @cgivre ! The change is forwarded to the PR now. I've less time lately to take care of the PR but hopefully I'll manage to do it in the following days.
